---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - "**/build/**/*"
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
Metrics:
  Enabled: false
Style/CombinableLoops:
  Enabled: true
  Exclude:
    - "**/benches/**/*.rb"
Style/Documentation:
  Enabled: false
