---
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "**/build/**/*"
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
    - "**/extn/**/*"
Metrics:
  Enabled: false
Style/CombinableLoops:
  Enabled: true
  Exclude:
    - "**/benches/**/*.rb"
Style/Documentation:
  Enabled: false
